### ISSUE TITLE
Create administrator failed with error message "sudo: A password is required "

### ISSUE THREAD

**Issue by pavananms** [bbatsche/Ansible-PostgreSQL-Install-Role#1]
Hi,
I am using the create administrator task. The task fails with following error on a remote host. I tried adding login user and login password and all. But it seems like its not logging in with postgres user .
Also, I can directly log into the remote host and run psql as the default postgres user. Then why should this fail?

TASK [bbatsche.PostgreSQL-Install : Create Administrator] **********************
fatal: [104.197.102.14]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE", "parsed": false}
    to retry, use: --limit @playbook.retry

**Comment by bbatsche** [comment]
If you look at that task, you will see that it has `become: yes`. That is because it is attempting to run a step as the `postgres` console user. As the error clearly states, you will need to provide the sudo password for your current user, or you may configure your user to perform passwordless sudo.
